# Site settings
author: Colin                 # 没找到在哪里显示的
baseurl: "/Collin_Blog"       # 点击brand时候要返回的地址，这个地方留成空的可以保证返回主页
brand: Mostly clear           # 主页面左上角的主页字体
copyright: whoever            # 主页面底下的copyright
description: Mostly clear     # 这个地方不是修改主页的title和description的，请到主目录的index.html中修改
email: colawithrain@gmail.com
title: Bye Bye Disco          # 这个是显示在浏览器标签上的名字
url: "https://colawithrain.github.io"

# Not using because Gulp is now processing SCSS
# sass:
#   sass_dir: css
#   style: compressed

# Algolia Search
algolia:
  application_id: 4P42FOBOZA # Use your (non-admin) search only api key here.
  index_name: sakura #Use an index you created on Algolia.

# Collections
collections:
  docs:
    output: true
    permalink: "/Collin_Blog/:collection/:path/"
  posts:
    output: true
    permalink: "/Collin_Blog/:collection/:title/"

# Defaults : these allow you to set default values for front matter
defaults:
  - scope:
      path: "/Collin_Blog/_posts"
      type: posts
    values:
      layout: post 
      type: post
  - scope:
      path: "/Collin_Blog/pages"
      type: pages
    values:
      layout: default 
  - scope:
      path: "/Collin_Blog/_docs"
      type: docs
    values:
      layout: post
      type: doc

# Exclude from Jekyll processing
exclude: [
  "_assets",
  "Gemfile",
  "Gemfile.lock",
  "gulpfile.js",
  "node_modules",
  "package.json",
  "publish.sh",
  "yarn-error.log",
  "yarn.lock"
]

# Pagination (using jekyll-paginate-v2)
pagination:
  enabled: true
  per_page: 4 
  paginate_path: "/Collin_Blog/page:num"
  sort_reverse: true
  title: ":title"
  trail:
    before: 2
    after: 2

# Plugins
plugins: [jekyll-paginate-v2, jemoji, jekyll-sitemap, jekyll-seo-tag]

# SEO
social:
  name: Colin
  links:
    - https://github.com/Colawithrain
webmaster_verifications:
  google: uubLfpcORmDWkM8pI-yKODVVZD3VSpUYFSwkQJcOuZE


# Social icons
show_social_icons: true
facebook_username: 
github_username: Colawithrain 
googleplus_username: 
linkedin_username: collin-lingzhi-cao # 这里填写linkedin个人链接最后面的username
slack_username: 
twitter_username: 

# Syntax highlighting <= disables built-in highlighter so that we can use Prism
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM